# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  swagger-generator-core-usual-test-oauth2:
    if: github.ref == 'refs/heads/test-flaky'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven
    - name: Compilation and Installation
      run: mvn clean install -DfailIfNoTests=false -pl swagger/swagger-generator/generator-core -Dtest=org.apache.servicecomb.swagger.generator.core.processor.annotation.SwaggerDefinitionProcessorTest#should_process_security_oauth2 -am

  swagger-generator-core-flaky-test-oauth2-nondex:
    if: github.ref == 'refs/heads/test-flaky'
    needs: swagger-generator-core-usual-test-oauth2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven
    - name: Compilation and Installation
      run: mvn clean install -DfailIfNoTests=false -pl swagger/swagger-generator/generator-core edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.servicecomb.swagger.generator.core.processor.annotation.SwaggerDefinitionProcessorTest#should_process_security_oauth2 -am

 # build:
 #   if: github.ref == 'refs/heads/master'
 #   runs-on: ubuntu-latest
 #   needs: swagger-generator-core-usual-test-oauth2
 #   steps:
 #   - uses: actions/checkout@v2
 #   - name: Set up JDK 1.8
 #     uses: actions/setup-java@v1
 #     with:
 #       java-version: 1.8
 #   - uses: actions/cache@v1
 #     with:
 #       path: ~/.m2/repository
 #       key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
 #       restore-keys: |
 #         ${{ runner.os }}-maven
 #   - name: Compilation and Installation
 #     run: bash scripts/build.sh install
 #   - name: publish coverage report
 #     run: bash <(curl -s https://codecov.io/bash)
